export default{
    START_FETCH_INDEX:'START_FETCH_INDEX',
    FETCH_INDEX_SUCCESS:'FETCH_INDEX_SUCCESS',
    FETCH_INDEX_FAILED:'FETCH_INDEX_FAILED',

    START_FETCH_MAJOR:'START_FETCH_MAJOR',
    FETCH_MAJOR_SUCCESS:'FETCH_MAJOR_SUCCESS',
    FETCH_MAJOR_FAILED:'FETCH_MAJOR_FAILED'
}